// <auto-generated />
namespace _02_BurgerMenu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig11));
        
        string IMigrationMetadata.Id
        {
            get { return "202410271157152_mig-11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
